name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: cache SBT
        uses: coursier/cache-action@v5
      - name: java ${{matrix.java}} setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{matrix.java}}
      - run: sbt "++${{matrix.scala}} test"
    strategy:
      matrix:
        java:
          - 8
          - 11
        scala:
          - 2.12.13
          - 2.13.5
